jobs:
  update_release_draft:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: release-drafter/release-drafter@v6
name: Changelog Release Drafter
on:
  repository_dispatch:
    types: trigger-ga___changelog-release-drafter.yml
