jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: Pull Request Auto Labeler
on:
  repository_dispatch:
    types: trigger-ga___labeler.yml
