jobs:
  build-jdk8:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.event_name == 'pull_request' && github.head_ref || github.sha}}
    name: Build project
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: '21'
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -version && whoami && umask -S && umask a+rw && umask -S && ./mvnw
        clean verify -P docker-clean -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
        -Dmaven.wagon.http.retryHandler.count=3 --no-snapshot-updates --batch-mode
        --no-transfer-progress
    - continue-on-error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
