jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{github.event.release.target_commitish}}
        token: ${{ secrets.RELEASE_PERSONAL_ACCESS_TOKEN }}
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: corretto
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        java-version: '21'
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      if: ${{ success() }}
      name: Update version
      run: ./mvnw --batch-mode --no-transfer-progress versions:set -DnewVersion=${{github.event.release.tag_name}}
        versions:commit
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      if: ${{ success() }}
      name: Publish to the Maven Central Repository
      run: ./mvnw --batch-mode --no-transfer-progress -Dgib.disable=true -P ossrh
        -DskipTests deploy
    - continue-on-error: true
      if: ${{ success() }}
      name: Commit & Push changes
      uses: actions-js/push@master
      with:
        branch: ${{ github.event.release.target_commitish }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: Release ${{github.event.release.tag_name}}
name: Publish to the Maven Central Repository
on:
  repository_dispatch:
    types: trigger-ga___release.yml
