jobs:
  renovate:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        DRY_RUN: ${{ inputs.dryRun || 'false' }}
        LOG_LEVEL: ${{ inputs.logLevel || 'debug' }}
      name: Self-hosted Renovate
      uses: renovatebot/github-action@v40.1.2
      with:
        configurationFile: .github/renovate/renovate.json
        token: ${{ secrets.RELEASE_PERSONAL_ACCESS_TOKEN }}
name: Renovate for update docker images
on:
  repository_dispatch:
    types: trigger-ga___renovate.yml
