jobs:
  label:
    if: github.event.pull_request.state == 'open'
    name: Verify Pull Request has labels
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: mheap/github-action-required-labels@v5
      with:
        count: 1
        labels: breaking-change, feature, enhancement, bug, dependencies, docker-update-images,
          documentation, housekeeping
        mode: minimum
name: Pull Request Required Labels
on:
  repository_dispatch:
    types: trigger-ga___required-labels.yml
